language: bash
services: docker
before_install:
  - cd RestWithSpringBootUdemy/
  - echo "We are in the Docker folder!"
script:
  - docker-compose build
before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
deploy:
  provider: script
  script:
    docker push matheusbonnet/mysql-curso_aws;
    docker push matheusbonnet/curso_aws;
  on:
    branch: master
notifications:
  email: false